version: '3.7'
services: 
  nginx: 
    image: nginx
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
      - "/etc/letsencrypt/:/etc/letsencrypt/"
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - front
      - gateway
  front: 
    image: feedback-forms-front
    build: ./feedback-forms-front
  gateway:
    image: feedback-forms-gateway
    build: ./feedback-forms-gateway
  mail: 
    image: feedback-forms-mail
    build: ./feedback-forms-mail
  average:
    image: feedback-form-average
    build: ./feedback-form-average
  consumer: 
    image: feedback-forms-consumer
    build: ./feedback-forms-consumer
  mongo:
    image: mongo
  queue:
    image: webcenter/activemq
